### PR TITLE
DOC: Fix use of \center vs. \centering in figures.

### PR DESCRIPTION
**Pull request by jhlegarreta**
According to the following LaTeX recommendations, `\centering` should be
used, rather than `\center` or `\begin{center}...\end{center}` which may
have undesired side-effects:

http://texblog.net/latex-archive/floats/center-centering/

https://tex.stackexchange.com/questions/23650/when-should-we-use-begincenter-instead-of-centering

https://tex.stackexchange.com/questions/2651/should-i-use-center-or-centering-for-figures-and-tables

Change-Id: I171a7866ac1fb00271ccc756c71a9dc8cb349564

### CODE REVIEW

**Comment by jhlegarreta** [comment]
It's not clear to me whether previous versions presented any issue concerning the vertical spacing, but if the canonical way to do it is using `\centering`, then let's see what this gives.

**Comment by jhlegarreta** [comment]
f9d3c4d rebased on master !
Having a CI build is awesome. Thanks @thewtex !

**Comment by thewtex** [comment]
Thanks for your patience, Jon, as we got the CI up!

**Comment by jhlegarreta** [comment]
Hats-off to you Kitware guys. You rock !

**Pull request merged**
