### PR TITLE
DOC: Add a Community Software Process appendix chapter.

### PR DESCRIPTION
**Pull request by jhlegarreta**
Add a Community Software Process appendix chapter to the ITK SW Guide
following the discussion in:
http://review.source.kitware.com/#/c/22654/

Change-Id: I53ba17103c3afb90987fc4f758b7128b198e31f3

### CODE REVIEW

**Comment by jhlegarreta** [comment]
@thewtex  @jcfr @fbudin69500  @hjmjohnson  reviews are welcome.

A few comments:
- Matt suggested a section for this in the SW Guide, so here it goes. I still think that a `Markdown` file in ITK would be more appropriate, but I am happy with the SW Guide chapter.
- The name of the file/chapter is the one Matt proposed. Although I thought that it may be named as "_Contributing to ITK with Git_" or "_ITK Git Workflow_" since it is tightly linked to Git, I left the one Matt proposed, since it conveys a broader idea.
- Rather than adding this as a new subsection of `Chapter Ten`, `Software Process`, I thought that due to its length it should rather go into an appendix, with the appropriate reference in that chapter.
- It has been an almost pure transcription with a few minor changes of the following wiki pages:

https://public.kitware.com/Wiki/Git/Download
https://public.kitware.com/Wiki/Git/Git/WorkflowPrimer
https://public.kitware.com/Wiki/Git/Workflow/Topic
https://public.kitware.com/Wiki/Git/Workflow/Topic/Conflicts
https://public.kitware.com/Wiki/Git/Workflow/Stage
https://public.kitware.com/Wiki/Git/Hooks
https://public.kitware.com/Wiki/Git/Publish
https://public.kitware.com/Wiki/ITK/Git/TipsAndTricks

- It may well happen that some sections are no longer valid (e.g. I ignore the existence of a `next` branch, some Git bash responses may be outdated, some commands be no longer of use, etc.). I've tried to update some links and contents that were clearly outdated, but I may have skipped some parts.
So reviews are welcome.

Comments about the **structure/form**:
- It looks like the deep nesting present in the wiki cannot be ported to the SW Guide, i.e. no more than two levels of sections under a chapter. Hence, many of the commands used (`\subsubsubsection`) are not recognized. Using the `\paragraph` command does not look like a good idea since it reduced the left/right margins. Any suggestions?
A consequence of this is that many of the crossrefs (e.g. those in the `Troubleshooting` columns in the wiki) do not work.
- I've used the `verbatim` environment for the ASCII-art parts. The `verbatim` environment does not allow for bold or italics. If we want bold or italics, we should switch to the either `fancyvrb` or `listings` packages, being the latter more powerful. I've got some MWE with them that I can share (e.g. in a gist or overleaf). I ignore whether the background color is not modifiable in the `verbatim` environment. In the current patch set, the default is transparent/white.
- I have not formatted the `Actions/Results/Troubleshooting` parts into tables since I could not check the result. But I've got a MWE that does use tables (I can paste it into a gist or overleaf). I'm open to suggestions.
- Each ASCII-art part can be put into a file `art.ascii` and be included as a picture. I don't know whether we think this is more appropriate. Alternatively, all `verbatim` environments can also be surrounded by a `picture` environment. I would be happy to make the necessary changes in either case.
- I have used the dollar sign (`$`) for `bash` commands, but it is not used in other parts of the SW Guide. If you want me to remove it, please let me know.


Specific comments about the **contents**:
- I've updated `MSysGit` to `Git for Windows`.
- I've used the official git-scm help pages (e.g. https://git-scm.com/docs/git-config) instead of the ones linked in the wiki (e.g. http://schacon.github.com/git/git-config.html). Are there any reasons (e.g. plain text) to keep the ones in teh wiki?
- As said earlier, the `next` branch seems exotic to me. In the `Published Branches` section of the [wiki](https://itk.org/Wiki/Git/Workflow/Topic), `main` (referred to as `maint` a few times), `master` and `next` are mentioned. I changed `main` (or `maint`?) for `release` and `next` for `stage`. Not sure about the latter.
- The link (https://www.kitware.com/Admin/SendPassword.cgi) in section `Authentication` requires a user/pass, which I don't recall having filled at the time. May be directions on which is the user should be added.
- Not sure whether I had to fulfil all steps in the `SSH on Windows` section when I first set up my environment.
- In the hooks section `commit-msg`, when talking about the subject line it is stated that:
`The first line must be between 8 and 78 characters long.`

But when exceeding 49 characters we get a warning in form of a colour change, right?
Besides, messages that are too long (not sure how many chars) appear with ellipsis in GitHub.

When talking about the commit summary, it is stated that:
`\item The third line and below may be free-form. (...) Try to keep paragraph text formatted in 72 columns (this is not enforced).`

Arer we sure that this is not enforced???
Is 72 right or is it 78?

- I've removed the a sentence that referenced `Windows XP` and `7` in section `SSH on Windows` for being these two too old in the [Publish](https://itk.org/Wiki/Git/Publish) section.
- I've kept the [code.google.com](https://code.google.com/archive/p/git-osx-installer/) link when talking about the Git `OS X installer` (section `macOS`). But the `code.google.com` page points to [sourceforge](https://sourceforge.net/projects/git-osx-installer/). Let me know if we want to point directly to sourceforge.

Thanks.

**Comment by thewtex** [comment]
Wow, Jon, awesome!!!

>  "ITK Git Workflow" 

I think that is better, too.

> \paragraph command does not look like a good idea since it reduced the left/right margins. Any suggestions?

Just a new line will generate a paragraph in LaTeX.

> If we want bold or italics, we should switch to the either fancyvrb or listings packages, being the latter more powerful. 

Feel free to go with what your experience and research dictate.

> I have not formatted the Actions/Results/Troubleshooting parts into tables since I could not check the result. But I've got a MWE that does use tables (I can paste it into a gist or overleaf). 

> Each ASCII-art part can be put into a file art.ascii and be included as a picture or [...]

Either way is fine I think. By the way, what is MWE?

> I have used the dollar sign ($) for bash commands, but it is not used in other parts of the SW Guide. If you want me to remove it, please let me know.

I think it is good to remove the dollar signs for consistency and to make copy/pasting easier.

> I've updated MSysGit to Git for Windows.

Good.

> I've used the official git-scm help pages

Good.

> As said earlier, the next branch seems exotic to me.

Yes, I think this could be omitted.

> The link (https://www.kitware.com/Admin/SendPassword.cgi) in section Authentication r

We will use GitHub for user management, so this does not need attention.

> But when exceeding 49 characters we get a warning in form of a colour change, right?

I will check this behavior when migrating the Git hooks for GitHub.

Thanks!

**Comment by jhlegarreta** [comment]
Thanks for the review Matt.

> \paragraph command does not look like a good idea since it reduced the left/right margins. Any suggestions?
> 
> Just a new line will generate a paragraph in LaTeX. 

Unfortunately, it's not about new lines or paragraphs, but about sectioning. It looks like there is a limit in the nesting or sectioning levels that is not enough for this chapter. So this is still unresolved.

> If we want bold or italics, we should switch to the either fancyvrb or listings packages, being the latter more powerful.
> 
> Feel free to go with what your experience and research dictate

Then I'll give fancyvrb a try. Have never used it before, and will introduce another dependency.  But I hope the result will be nicer. 

MWE: Minimal Working Example ?

OK, I'll remove the dollar signs.

> We will use GitHub for user management, so this does not need attention.

Then I'll change the concerned paragraphs.

**Comment by jhlegarreta** [comment]
Could anybody please generate the SW Guide based on this PR just so that I can see what this is giving?

Still unable to generate the SW Guide PDF locally, arrggh.

May be @fbudin69500 ?

Thanks.

**Comment by jhlegarreta** [comment]
f6c789a changes:
* Change the chapter name to `ITK Git Workflow`
* Fix some syntax oversights (misspelled LaTeX commands, open-ended braces, etc.).
* Remove the dollar sign from bash code samples.

Now if `\subsubsubsection` and `\subsubsubsubsection` are changed to `\subsubsection` the file can be compiled.

Will work on the git worklfow diagrams and GitHub authentication paragraph for the next patch set.

**Comment by jhlegarreta** [comment]
Commit 674e574 fixes some encoding issues.

**Comment by jhlegarreta** [comment]
Folks, the following overleaf link contains a version of the ITK Git workflow chapter at its current state:
https://www.overleaf.com/read/ctvndbxrrydh

I've been trying to overcome the issues when setting a background color to the **ASCII-art parts to reproduce the git branching workflows as faithfully as possible**.  Their use is shown in the `New Topic` (p. 7) section, where tables are required and things start to be complicated:.

The most basic use of the environments for the ASCII-parts use is demonstrated here:
https://www.overleaf.com/read/mtwtdbzrxqph

The following are some comments I'd like to make about the formatting of the git branching diagrams:

- The `verbatim` environment does not allow us to easily render the text with a background color, so other solutions are necessary.

- The `lstlisting` environment requires defining (and using) an escape character/sequence to produce bold/italics fonts, e.g.:
```
\usepackage{listings}
\usepackage[latin1]{inputenc}
\lstset{backgroundcolor=\color{verbgray},
  basicstyle=\ttfamily,
  frame=single,
  escapeinside={||},
  mathescape=false}
```
to be able to use:

```
\begin{lstlisting}
*|\textbf{master}|
$a_{i}
|a\textsubscript{i}|
|\$| Escaped command line statement
\end{lstlisting}
```
which I do not think is practical/too smart. Besides it is used for the `captionsetup` (\Latex\00-Preamble-Common.tex), and I ignore whether using the `lstset` would end up having some kind of clash with the captions once the whole document compiled.

- Using the `Verbatim` environment allows us to use bold/italics:
```
\usepackage{fancyvrb}
\usepackage{bera}
\fvset{frame=single,
framerule=0.4pt,framesep=\fboxsep,
rulecolor=none,
fillcolor=\color{yellow}}
```

to be able to write:
```
\begin{Verbatim}[commandchars=\\\{\},codes={\catcode`$=3\catcode`_=8}]
code line 1
$a_{i}$
code line 2
\textbf{boldfaced text}
a\textsubscript{i}
\end{Verbatim}
```
However, its rendering does not quite fit into our expectations, since the `fillcolor` only draws a frame around the text, and does not represent a real background color fill. So it is not a valid solution.

The use of the `[commandchars=\\\{\},codes={\catcode`$=3\catcode`_=8}]` options each time we use the environments seems to be unavoidable; i.e. I have not found a way to define that somewhere and make all `Verbatim`s adopt those options.

- Using the options to customize `Verbatim` environment offered by the `fancyvrb`, we could define how we want the `box verbatim`(`BVerbatim`) want to be:
```
\definecolor{verbgray}{gray}{0.95}
\definecolor{framegray}{gray}{0.8}

\makeatletter
\newif\ifFV@bgcolor
\newbox\FV@bgbox
\define@key{FV}{bgcolor}{\FV@bgcolortrue\def\FV@bgcolor{#1}}
\def\FV@bgcolor{verbgray}
\define@key{FV}{framecolor}{\FV@bgcolortrue\def\FV@framecolor{#1}}
\def\FV@framecolor{framegray}

\def\FV@BeginVBox{%
  \leavevmode\ifFV@bgcolor\setbox\FV@bgbox=\fi
  \hbox\ifx\FV@boxwidth\relax\else to\FV@boxwidth\fi\bgroup
  \ifcase\FV@baseline\vbox\or\vtop\or$\vcenter\fi\bgroup}
\def\FV@EndVBox{\egroup\ifmmode$\fi\hfil\egroup
  \ifFV@bgcolor\fcolorbox{\FV@framecolor}{\FV@bgcolor}{\box\FV@bgbox}\fi}
\makeatother
```

to be able to write:
```
\begin{BVerbatim}[commandchars=\\\{\},bgcolor=verbgray,framecolor=framegray,boxwidth=\textwidth]
code line 1
$a_{i}$
code line 2
\textbf{boldfaced text}
a\textsubscript{i}
\$ Escaped command line statement
\end{BVerbatim}
```

which ressembles what we want to achieve. However, it justifies the box in a such a way that it is not centered or left/right flushed with the text. It also makes the subsequent paragraphs all the way down to the end of the document to be slightly indented. So a `\raggedright` statement is necessary at the beginning of the document. Other than that, if no boxwidth is defined, the width is fit to the contents.

So it pretty much what we want to achieve.

- The last alternative is a variant from the former, where a custom `CVerbatim` is defined using a `tcolorbox`:
```
\newenvironment{CVerbatim}
{\VerbatimEnvironment
  \begin{tcolorbox}[
    breakable,
    colback=verbgray,
    spartan,
    left=0pt,
    right=0pt,
    top=0pt,
    bottom=0pt,
    colframe=framegray,
    boxrule=0.4pt
    ]%
\begin{Verbatim}}
{\end{Verbatim}\end{tcolorbox}}
\fvset{frame=none}
```

which allows us to write:
```
\begin{CVerbatim}[commandchars=\\\{\},codes={\catcode`$=3\catcode`_=8}]
code line 1
$a_{i}$
code line 2
\textbf{boldfaced text}
a\textsubscript{i}
\$ Escaped command line statement
\end{CVerbatim}
```

Again, the result is similar to what we want to achieve.

Putting all these into tables causes some overlap issues yet:
- The `BVerbatim` boxes overlap slightly vertically and horizontally; the former may be something that could be fixed somehow although I have not checked/tried; the latter is due to the fact that the boxes adapt to the width of their content unless otherwise specified, and despite the column width. If the `breaklines=true` option is added to `fvset`, the lines in a `Verbatim` environment are broken, but not those in `BVerbatim`. Using `lll` as the column specifier will result in issues if all three columns are too wide.
- The `CVerbatim` boxes overlap horizontally; if the `breaklines=true` option is added to `fvset`, the lines are broken, but a CR/LF character is added. I would not be bothered about seeing it.

`lstlisting` does allow for line breaking.

So the use of tables makes `CVerbatim` the only suitable candidate.

An issue that is present in the file is that the `minted` environment seems not to be working well inside tables.

Another stepping stone in all this would be the existence of so many tables and verbatim environments that unless the ITK SW Guide uses some LaTeX mechanism to enforce their location, they will be put wherever LaTeX finds enought room (i.e. not where they should appear).

I may understand that the table layout may not be the best, especially the troubleshooting column, so I'm open to suggestions.

Also, I understand that adding the diagrams in table form, including a caption my not be desirable.

So I'm open to hear your comments. Thanks.

At least, we now know the formatting required (or the issues the alternatives may present) to reproduce the git branching diagrams.

**Comment by jhlegarreta** [comment]
Interestingly enough, dropping the `minted` environment options:
```
\begin{table}
\begin{center}
\begin{tabular}{G{0.3\textwidth} p{0.3\textwidth} p{0.3\textwidth}}
\hline
\textbf{Actions} & \textbf{Results} & \textbf{Troubleshooting} \\
\hline
\begin{minted}{bash}
git checkout master
\end{minted}
&
\begin{CVerbatim}[commandchars=\\\{\},codes={\catcode`$=3\catcode`_=8}]
...o *\textbf{master}
\end{CVerbatim}
& \\
\begin{minted}{bash}
git pull
\end{minted}
&
\begin{CVerbatim}[commandchars=\\\{\},codes={\catcode`$=3\catcode`_=8}]
...o----o *\textbf{master}
\end{CVerbatim}
& \\
\multicolumn{3}{p{\linewidth}}{Create the local topic branch. Use a meaningful name for \textit{topic} (see
Section~\ref{subsubsubsec:NamingTopics} on
page~\pageref{subsubsubsec:NamingTopics}).}\\
\begin{minted}{bash}
git checkout -b \textit{topic}
\end{minted}
&
\begin{CVerbatim}[commandchars=\\\{\},codes={\catcode`$=3\catcode`_=8}]
...o----o master
        ^ *\textbf{\textit{topic}}
\end{CVerbatim}
& \\
\end{tabular}
\end{center}
\caption{\textit{minted} for command line codes used in combination with \textit{CVerbatim} for git branching diagrams.\label{tab:Label}}
\end{table}
```

make the `git` commands be rendered without that awkward layout inside tables , but:
- We'd not be able to keep consistency concerning the `minted` environment **background color** with he rest of the SW Guide.
- Column-wise **alignment issues** appear.

Finally, I realize that the font commands do not work inside a `minted`  environment (e.g. `git checkout -b \textit{topic}`), and hence, we may be forced to use the `CVerbatim` option suggested to achieve the same effect as in the wiki git branching diagrams.

**Comment by thewtex** [comment]
Very nice, @jhlegarreta !

I think we no longer have to be constrained by ASCII diagrams and could use something better with LaTeX. This would also get around the verbatim issues encountered. Maybe use figures like the one in [the second answer to this question](https://tex.stackexchange.com/questions/125244/how-can-i-produce-the-history-graph-of-a-git-repository-in-latex) using [gitdags](https://github.com/Jubobs/gitdags).

**Comment by jhlegarreta** [comment]
Nice finding @thewtex ! Thanks. It could be a solution. Although it will require some reformatting/change. Have a look at p. 5 in
https://www.overleaf.com/read/ctvndbxrrydh

Font style changes seem not to be allowed inside boxes. A workaround is to define new commands for that. I'll try to see with the LaTeX style file author.

Yet, I still do not see a solution for the issue with the `minted` environment in the tables (see Table 1.6).

**Comment by thewtex** [comment]
@jhlegarreta That diagram is beautiful! :nail_care: 

Yes, `CVerbatim` fine in the tables in my humble opinion. Black and white is more readable in the table I think, regardless.

**Comment by hjmjohnson** [comment]
@jhlegarreta @thewtex This is incredibly fabulous.  I think this draft is suitable for inclusion now, and subsequent changes could be added later.

**Comment by jhlegarreta** [comment]
@hjmjohnson thanks for the review.

I just gathered most if not all the ITK wiki contents that applied. Yet, I feel that it is quite likely that this needs a major revision, since:
* Switching to GitHub will probably require changes to this workflow. But this will need to be addressed at the right time.
* The `next` branch is something that I've removed without a clear criterion. I ignore whether this refers to the git `index`; or whether it refers to what is called `stage` in the current ITK workflow; or else, whether it referred to some other step that was/is important to the ITK workflow (at that time). So unfortunately the contents require a major revision.

I still need to try and master the gitdag tool to rework the git branching diagrams. And that may take a while. I am thinking of trying to reproduce the Pro Git book diagrams' look&feel (e.g. [1]); I'd love to have some tool with the power of gitgraphjs [2], but for the moment, we will need to content ourselves with gitdags, which is still nice and useful.

One of the concerns I have wrt the tables is that the branching diagrams are likely to be too large to fit into the (wiki) table layout (actions/results/troubleshooting [3]). I have to make some tests yet to see the result, but even if I got to resize the diagrams, I fear that they would be too small.

[1] https://git-scm.com/book/en/v2/Git-Branching-Branches-in-a-Nutshell
[2] http://gitgraphjs.com/
[3] https://itk.org/Wiki/Git/Workflow/Topic

**Comment by thewtex** [comment]
We will see how the GitHub process pans out, but at first we will start simple, without `stage` or `next`.

**Comment by jhlegarreta** [comment]
Folks,
I've been further working on this. One step closer to merging :-)

I think I am mostly done **transitioning the ASCII-art to gitdags**, except a couple of cases. But before further working on this, I'd like to hear from you.

I think having the graphs in tables, beyond those in the notation subsection, does not yield a nice result. Please have a look at the example in Table 1.7 on p. 10 for the `git merge` command in the Wiki equivalent in ' New Topic` section.
https://www.overleaf.com/11570966hggxpftdsmsm#/43763906/

The above stills needs some housekeeping (remove no longer needed `Verbatim` environment samples, etc.), but I've implemented a non-negligible amount of git diagrams.

I think vertical horizontal and vertical alignment issues could be fixed, but for some large graphs, we may exceed the page width unless scaling.

The available width in the PDF is smaller than for the Wiki. Scaling the tikzpicture would potentially make some graphs unreadable.

And even for small/medium size graphs, we wouldn't be able to add the **Troubleshooting** the column due to the horizontal space.

Whether we use tables or not, we will probably run into **positioning issues** as well, since some text or command line parts will refer to figures in previous/subsequent pages, which make the text difficult to follow. However, using tables would position all on the same page, at least for those that actually use tables in the Wiki.

If we finally adopt the `gitdags` package to draw Git graphs, then bold and italics font related attempts (i.e. `lstlisting`, `Verbatim`, `BVerbatim`, `CVerbatim`, etc. environments) are no longer useful. I'd create new gitdag commands to make the tag text be bold, italics, etc.

Also, note that at times I've removed the `next` branch from the graph, especially in the `Topic` section:
https://itk.org/Wiki/Git/Workflow/Topic

Hence, the `New Topic` and `Mature Topic` subsection graphs have no difference. Thus, we should either remove and rename one.

In the `Conflicts` section I've substituted with `release`:
https://itk.org/Wiki/Git/Workflow/Topic/Conflicts

but I am not sure whether this equivalency is completely OK

Also, we have a `Stage` section in the Wiki; if this does no longer make sense for our current workflow, I'd rule it out (kept it in all patch sets until a decision is made). Thus, this sections git diagrams are still ASCII-art until we decide what to do with it.

Else, I'm wondering whether I it is more sensible to keep all next/stage appearances/section untouched if they still make sense, until they do not (e.g. transition to GitHub).

Finally, I haven't made any **distinction between** the `Commit with parent in same branch` and `Commit with arbitrary ancestry` throughout the document. Although adding a commit with ellipsis to represent `Commit with arbitrary ancestry` is an option to do this, I think it does not add valuable information in the gitdag diagrams. If you think it is useful, let me know.

Note that in the mentioned overleaf draft mirror I was forced to rule out some sections since overleaf was yielding a compile timeout due to the large number of itkz graphs it had.

**Comment by thewtex** [comment]
This is beautiful, Jon!

> I think I am mostly done transitioning the ASCII-art to gitdags, except a couple of cases. But before further working on this, I'd like to hear from you.

+1. The gitdag look very nice, and they are easy to follow. That said, the ASCII-art works, too.

> I think having the graphs in tables, beyond those in the notation subsection, does not yield a nice result. 

> [...]
> And even for small/medium size graphs, we wouldn't be able to add the Troubleshooting the column due to the horizontal space.
> [...]

Yes, if tables are used, leaving the *Troubleshooting* column out will fit with content better. Troubleshooting tips could go in the caption, etc. Or, we could just forgo the tables.

> [...]
> Else, I'm wondering whether I it is more sensible to keep all next/stage appearances/section untouched if they still make sense, until they do not (e.g. transition to GitHub).
> [...]

I think we should leave the multi-integration branch content out, i.e. `stage`, `next`-related, etc. This is hard for new contributors to follow, and it adds more complexity and burden than practical benefit in use in my opinion. Moreover, it requires CI resources, which ITK does not have at the moment, to really be useful. We could add it back if / when it can make a significant benefit, but I think it should be left out to avoid confusing new community members.

> Finally, I haven't made any distinction between the Commit with parent in same branch and Commit with arbitrary ancestry throughout the document. 

This reasonably avoids adding distracting complexity to the diagram without leaving out critical information to the reader in my opinion. The reader can assume, or we could explicitly state that, branches are created from `release` or `master` unless specified otherwise.

> Else, I'm wondering whether I it is more sensible to keep all next/stage appearances/section untouched if they still make sense, until they do not (e.g. transition to GitHub).

The Overleaf link is cool. I use Overleaf for papers and proposals, and I love it. But, as you mentioned, some the previous Overleaf links sent were crashing in my browser (the recent one works for me).

If the branch is rebased on master, CircleCI will build it and push the generated PDF as a link in the CDash Experimental group. I am working on generating a GitHub PR comment so we can get a direct link to the CDash builds.

**Comment by jhlegarreta** [comment]
@thewtex Thanks for the review and comments.

Then
- I'm leaving the tables and the troubleshooting column out.
- I'm leaving the multi-integration branch references out.
- I removed the `Stage` [wiki chapter](https://itk.org/Wiki/Git/Workflow/Stage) from the document.

Also
- I added the labels to the gitdag figures.
- I removed the `Commit with parent in another branch` from the `Notation` section

> If the branch is rebased on master, CircleCI will build it and push the generated PDF as a link in the CDash Experimental group. I am working on generating a GitHub PR comment so we can get a direct link to the CDash builds.

Sounds awesome !! 346a1dc was rebased on master. Although I've also made these changes to the overleaf version for a fast inspection, I will look at the PDF produced by CircleCI.

Once style issues, big questions solved, the document may need some revision.

I'd propose leaving modifying the look and feel of the graphs for another topic to push things forward.

**Comment by thewtex** [comment]
Excellent, Jon -- sounds like a great plan!

The CI build found an issue :-)

```
! LaTeX Error: Environment tikzpicture undefined.
```

**Comment by jhlegarreta** [comment]
@thewtex Thanks for keeping an eye on this !

The `tikzpicture` environment is defined in the `tikz` package, as shown [here](https://en.wikibooks.org/wiki/LaTeX/PGF/TikZ#Loading_Package,_Libraries_-_tikzpicture_environment) or [here](https://www.sharelatex.com/learn/TikZ_package),

And the  `tikz` pacakge is required by `gitdags` [here](https://github.com/jhlegarreta/ITKSoftwareGuide/blob/346a1dc1ef6450e20db6d8a5e9e4fa9e805de17f/Latex/gitdags.sty#L28).

The overleaf projects I've used (see [the graphs](https://www.overleaf.com/12724157hzdsctkgvvkm#/48540382/) and [the main text](https://www.overleaf.com/11570966hggxpftdsmsm#/43763906/)) to build the graphs prior to pushing this seem not to find issues when using this package.

I'm wondering whether our **docker** instance or the LaTeX environment that it uses is able to **download the required packages on-the-fly**.

Looks like the **required LaTeX packages in our docker instance dwell in**
```
/usr/share/texlive/texmf-dist/tex/latex/
```

And I have not found `tikz` among them. May be we need to add the `tikz` package to the [docker image](https://github.com/InsightSoftwareConsortium/ITKSoftwareGuide/blob/a78832ff17ab4c40dfa4b5728d6354d643fec05c/.circleci/config.yml#L7) we use?

**Comment by hjmjohnson** [comment]
I agree with @jhlegarreta .  tikz is a common package and should be acceptable to use in our latex documentation.  

It will be nice to get this long-standing improvement incorporated.

**Comment by thewtex** [comment]
I will investigate whether we need additional packages in the Docker image or if there is some other change that will make it compile...

**Comment by thewtex** [comment]
@jhlegarreta @hjmjohnson Added a commit that addresses the build in the Docker image locally.

**Comment by jhlegarreta** [comment]
Solved the missing cross-refs. Rebased on master.

Let's see what the CI build gives.

**Comment by jhlegarreta** [comment]
@hjmjohnson @thewtex Thanks for the approvals folks !

However, I checked the dashboard build and spot (still) some missing cross-refs. Sorry. *Mea culpa*; it looks like I missed some in the commit a couple of days ago.

Let's see if I got them all right now. I had also forgot to remove the remaining references to the **Stage** [wiki chapter](https://itk.org/Wiki/Git/Workflow/Stage).

I'm really sorry for not being able to catch up lately and all these oversights that generate new notifications and making this PR eternal.

Thanks for understanding.

**Comment by hjmjohnson** [comment]
@jhlegarreta THANK YOU for shepherding this important work to completion.

**Comment by jhlegarreta** [comment]
No cross-refs missing ! Awesome.

**Pull request merged**
