### PR TITLE
BUG: Fix Table 2.1 exceeding the page width.

### LINKED ISSUE #62: Table 2.1 exceeds the page/paragraph width
Table 2.1 about the compiler support timeline ([page 11](https://www.itk.org/ItkSoftwareGuide.pdf)) seems to exceed the page/paragraph width.

### PR DESCRIPTION
**Pull request by jhlegarreta**
Fix `Table 2.1` in chapter `CONFIGURING AND BUILDING ITK` exceeding the
page width.

Fixes #62.

### CODE REVIEW

**Comment by jhlegarreta** [comment]
Not sure if the rendered table will be too small.

If it is, an alternative would be to use a landscape layout on a page of its own. Looks like there are a number of alternatives:

- Using the `rotating` or the `afterpage` packages:
https://tex.stackexchange.com/questions/19017/how-to-place-a-table-on-a-new-page-with-landscape-orientation-without-clearing-t

- Using the `lscape` package:
https://tex.stackexchange.com/questions/345483/horizontal-page-for-largetables/345484

- Using the `pdflscape` package:
https://texblog.org/2007/11/10/landscape-in-latex/

I've tested `rotating`, `pdflscape` and `lscape` in some separete, MWEs and all seem to work well. `rotating` and `lscape` just rotate the content, whereas `pdflscape` rotates the page itself as well, which I ignore whether it is desirable. Finally, `rotating` requires using the command `\begin{sidewaystable}` whereas `lscape` does not (just using `\begin{landscape} \end{landscape}` around the table). Either are fine for me if the rest of the pages before/after render OK.

**Comment by jhlegarreta** [comment]
Thanks for the review @thewtex ! Commit 5bf45e4 implements a landscape orientation for the table while keeping the portrait orientation for the page. Let's check whether the output provided by the CI builds is according to the expectations.

**Comment by thewtex** [comment]
:+1: Cool, @jhlegarreta !

The build is failing. Do we need `\usepackage{rotating}`?

**Comment by jhlegarreta** [comment]
Yes, sorry for the oversight @thewtex. a212164 addresses this. Thanks for the review.

**Comment by jhlegarreta** [comment]
Thanks @thewtex. Nonetheless, I've checked the [output](https://open.cdash.org/upload/fa30d0ce121c271efd635e3c38a51dd9f3c34a7b/ITKSoftwareGuide-Book1.pdf) and it does not quite look like we expected. I need to investigate further.

**Comment by jhlegarreta** [comment]
Included the legend in the `sidewaystable` environment, which I guess we want. Also, since the table is not immediately below the cross-reference, used colon instead of period.

The table overlapping the header is still unsolved. I've been looking for a solution without success. Will try to look better.

**Comment by jhlegarreta** [comment]
One option that I do not particularly like (since it is a workaround rather than a solution) is to change the font size in the table to `small`. Another one is customize the header for float-only pages, as suggested [in this post](https://tex.stackexchange.com/questions/229472/problem-between-sidewaystable-and-page-header/229475). But again, that may have undesired effects on pages that may be difficult to spot in a long document like ours.

**Comment by jhlegarreta** [comment]
I do not see an explanation to the CI build failure. @thewtex how can I re-run the CI build?

**Comment by thewtex** [comment]
@jhlegarreta When you click the `Details` link next to `ci/circleci: build`, there should be a button, *Rerun job with SSH*. You can click that, and it will restart the job but also provide a temporary ssh command to log into the system, inspect outputs, etc. If the button is not there, please let me know, and we will get you the required permissions.

**Comment by jhlegarreta** [comment]
@thewtex that's right: I had already navigated to the cicle CI build to inspect the output and tried *Rerun job with SSH* but it is not a clickable button for my user it appears. I get the *You need write permissions to trigger builds* message when I hover it.

**Comment by thewtex** [comment]
@jhlegarreta That's interesting -- maybe a CircleCI bug? You are on the *ITKSoftwareGuide developers* team, which has *Admin* privileges on the repository.

I added your account to the *Collaborators* for the repository with *Write* access. Please try again to see if that does it.

**Comment by jhlegarreta** [comment]
Sorry, @thewtex , still the same result.

**Comment by thewtex** [comment]
How about after pushing to the branch?

**Comment by jhlegarreta** [comment]
Will try tomorrow afternoon then. Thanks for the suggestion !

**Comment by jhlegarreta** [comment]
@thewtex I discovered why: I did not have my GitHub account connected in my circle CI ' Account Integration` settings. Now, I ignore whether just being part of the Admins would have been enough... Sorry Matt.  Re-running the job now...

**Comment by thewtex** [comment]
Ah, that was tricky. Thanks for taking a look, @jhlegarreta

**Comment by jhlegarreta** [comment]
This is weird: checking out the code for the commit hash at issue (caa048f) is failing in circle CI:
```
fatal: Could not parse object 'caa048fe9d21116f734f4557fcd635a83215cd42'.
```
No idea why this should be happening.

**Comment by thewtex** [comment]
@jhlegarreta that is odd...

Since  `caa048fe9d21116f734f4557fcd635a83215cd42` is the commit on this branch, please try changing the content, then `git commit --amend` so a new commit is created, then force pushing.

**Comment by jhlegarreta** [comment]
@thewtex Sorry for the delay :grimacing: I've just rebased and pushed. Let's see what the CI builds tell, and if we're able to solve this.

**Comment by jhlegarreta** [comment]
Patch set c7bc943 still showed a table stepping into the header. An alternative to make the table smaller is
```
\usepackage{lscape}
....
\begin{landscape}
\begin{table}
\begin{center}
\resizebox{1.6\textheight}{!}{
\begin{tabular}{c c c c c c c c c c c c c c c c c}
\toprule
...
\end{tabular} }
\end{center}
...
```

But still the look of a lonely table in a single page did not look nice to me, and hence in f7fb0f6 I opted for coming back to a portrait orientation table but limiting its width. If we are happy with the result, I'll update the commit message and this will be ready to be merged.

**Comment by jhlegarreta** [comment]
The result looks satisfactory to me. Check it at
https://open.cdash.org/upload/c775d762a71fe6cf7f601d62263f8887f39d8140/ITKSoftwareGuide-Book1.pdf

It's just the position that LaTeX chose that makes the compiler list time schedule be broken that is not that nice. I've added a `[h]` in 4aaf5b3 to see if that forces LaTeX choose a better position and avoids breaking the list.

Updated the commit message.

**Comment by jhlegarreta** [comment]
Looked OK to me but for the legend: I forgot to force its position :blush:.  It should look OK in 960378f !

**Comment by jhlegarreta** [comment]
It does look OK to me :ok_hand: now !

**Pull request merged**
