### PR TITLE
ENH: Bump ITK to 5.0a02

### PR DESCRIPTION
**Pull request by thewtex**
Build has been pushed to itk.org:

  https://itk.org/ITKSoftwareGuide/html/

### CODE REVIEW

**Comment by thewtex** [comment]
Thanks for the reviews @dzenanz @jhlegarreta .

I would like to understand the build failure. I will take pass at addressing the line length warnings.

**Comment by thewtex** [comment]
Patch here:

  http://review.source.kitware.com/#/c/23473/

**Comment by jhlegarreta** [comment]
@thewtex thanks !! I was willing to address the line length warnings for a long time (too long) but you beat me. That will help reducing the number of LaTeX warnings and to stay focused.

**Comment by thewtex** [comment]
@hjmjohnson This merge broke the CI, which is critical to keeping the project working and moving forward. Can you please follow up with a fix?

**Comment by hjmjohnson** [comment]
@thewtex I'll look closer later today.  I'm in the middle of getting the remote modules working with VXL 2.0.0.

The large number of approved PR's that were not merged was causing hours of merge conflicts so I tried to get the approved PR's pushed in to minimize the combinatorial set of code bases that needed working with.

**Comment by thewtex** [comment]
@hjmjohnson thanks!

**Pull request merged**
