### PR TITLE
DOC: Fix typos in PDF document properties.

### PR DESCRIPTION
**Pull request by jhlegarreta**
Fix the missing escape character to write accents in the PDF document
properties.

### CODE REVIEW

**Comment by jhlegarreta** [comment]
BTW, does anyone happen to know why the **PDF properties** are **not correctly set** for **book 2**? Just have a look at one of the recent CDash builds, e.g.
https://github.com/InsightSoftwareConsortium/ITKSoftwareGuide/pull/69
and the PDF file to check the properties:
[ITKSoftware Guide Book 1 PR 69](https://open.cdash.org/upload/5ff578cf478e77cae4ec9b6383782879cb7c375d/ITKSoftwareGuide-Book1.pdf)

**Comment by thewtex** [comment]
Thanks, @jhlegarreta . 

I am not familiar with the PDF properies issue.

**Comment by jhlegarreta** [comment]
I use Adobe Acrobat Reader DC, but any other (?) allowing you to view the file should be fine. I ignore whether Chrome allows you explore the file properties. 

Once downloaded, in Acrobat Reader DC at least, you open the file, then click the `File` menu, then the `Properties` section, and there you can examine the title given, the **author**, **subject**, **keywords**, etc.

**Comment by dzenanz** [comment]
Adobe's reader is authoritative, if this patch fixes the appearance in it it should be merged.

**Comment by jhlegarreta** [comment]
Same result as before; trying adding
```
\usepackage[
  pdfencoding=auto,% or unicode
  psdextra,
]{hyperref}
```

in 76354a1.

**Comment by dzenanz** [comment]
Below is the header from my [thesis](http://www.cg.informatik.uni-siegen.de/data/Publications/2014/Dissertation_Dzenan_Zukic.pdf). My name contains accents and you can check whether they appear correctly in the generated document :smile: 
```tex
\documentclass[a4paper,11pt,final]{book}
\usepackage[american,ngerman]{babel}
%\usepackage[hyphens]{url}
%\makeatletter
%\g@addto@macro{\UrlBreaks}{\UrlOrds}
%\makeatother
\usepackage[T1]{fontenc}
\usepackage{textcomp}
\usepackage[sc]{mathpazo}
\linespread{1.05}        % Palatino needs more leading (space between lines)
\usepackage{courier}
\usepackage{varioref}
%\vrefwarning
\usepackage{graphicx}
\usepackage[svgnames]{xcolor}
%\usepackage{fixltx2e} %fixltx2e is not required with releases after 2015
\usepackage{booktabs}
\usepackage{multirow}
\usepackage{dcolumn}
\newcolumntype{d}[1]{D{.}{.}{#1} }
\usepackage{fancyhdr}
\usepackage{listings}
\usepackage{amsmath}
\usepackage{rotating}
\usepackage{thesis}
\usepackage{cite}
\usepackage{subfig}
\usepackage[utf8]{inputenc}
\PassOptionsToPackage{hyphens}{url}\usepackage[unicode=true,pagebackref=true]{hyperref}
%\usepackage[pdfborder={0 0 0}]{hyperref}
\hypersetup{
    pdftitle={An Efficient Inflation Method for Segmentation of Medical 3D Images},
    pdfauthor={Dženan Zukić},
    pdfpagelayout={TwoColumnRight},
}
% \usepackage{cleveref}
\usepackage[all]{hypcap}
\usepackage{hyphenat}
\usepackage{microtype}
\usepackage{textcomp}
\usepackage[labelfont=bf,indention=5mm,parskip=1mm]{caption}
\usepackage{parskip}
\setlength{\parindent}{5mm}

\renewcommand{\topfraction}{.85}
\renewcommand{\bottomfraction}{.7}
\renewcommand{\textfraction}{.15}
\renewcommand{\floatpagefraction}{.66}
\renewcommand{\dbltopfraction}{.66}
\renewcommand{\dblfloatpagefraction}{.66}
\setcounter{topnumber}{9}
\setcounter{bottomnumber}{9}
\setcounter{totalnumber}{20}
\setcounter{dbltopnumber}{9}
%\setcounter{secnumdepth}{3}
%\setcounter{tocdepth}{3}

\usepackage[section]{placeins}
\usepackage[all]{nowidow}
\pdfsuppresswarningpagegroup=1 %introduced with pdflatex 1.40.15

\begin{document}
```

**Comment by jhlegarreta** [comment]
Thanks for the input @dzenanz.

Unfortunately, GitHub does not display the results for 76354a1; and I already committed 8c5883f. However, in a local test I made, the addition
```
\usepackage[
  pdfencoding=auto,
  psdextra,
]{hyperref}
```
did not do the trick.

However, I think I found a workaround :smile:. [This post](https://tex.stackexchange.com/questions/12981/using-non-ascii-characters-in-author-names-and-titles-within-hyperref-pdfinfo?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa) suggested using the `hypersetup` environment for the PDF file properties instead of setting them in the `usepackage` importation step.

And voilà, it worked in a small document I made with the ITK SWG properties. Cool !!

Let's see what CDash say to 8c5883f.

Now, we may need more time or another topic for the book 2 properties mystery.

**Comment by jhlegarreta** [comment]
@thewtex thanks for the review ! @dzenanz thanks for all the comments and also helping find the solution !

I've checked that the PDF properties are fixed for Book 1; the properties of Book 2 remain unchanged; I'll open an issue, have a look at it and hopefully propose a fix in another topic to push things forward.

Merging.

**Pull request merged**
