### PR TITLE
ENH: Add GitHub Action to build and publish Guide PDFs

### PR DESCRIPTION
**Pull request by thewtex**

### CODE REVIEW

**Comment by hjmjohnson** [comment]
Very exciting!  it will be great once this is debugged more.

**Comment by thewtex** [comment]
> Maybe the Circle CI script can be deleted also in this PR?

Yes! Done.

**Comment by jhlegarreta** [comment]
> Yes! Done.

Thanks Matt. The `README` Circle CI badge should also be changed to the new GitHub Actions badge. Sorry, I should have mentioned it before.

**Comment by thewtex** [comment]
> Thanks Matt. The README Circle CI badge should also be changed to the new GitHub Actions badge. Sorry, I should have realized before.

Thanks for catching that, too, Jon Haitz.

**Pull request merged**
