### PR TITLE
ENH: Improve git pr detection of Python 3 when python3 not available

### PR DESCRIPTION
**Pull request by thewtex**
Detect Python 3 when only the python executable is available.

### CODE REVIEW

**Comment by thewtex** [comment]
Thanks for testing, Jon.

It sounds like `python --version` unexpectedly prints to `stderr` instead  `stdout` -- a new versions that should address this has been uploaded if you could please test it.

**Comment by jhlegarreta** [comment]
OK. I had missed the update. Will give it a try during the weekend.

**Comment by jhlegarreta** [comment]
Works like a charm 🎆 :
```
$ git pr
57: ENH: Improve git pr detection of Python 3 when python3 not available
59: DOC: Add auto usage to the Coding Style Guide

Pull request number? [59]:
From https://github.com/InsightSoftwareConsortium/ITKSoftwareGuide
 * [new ref]         refs/pull/59/head -> pr/59
error: unable to create file Utilities/GitSetup/git-pr (Permission denied)
D       Utilities/GitSetup/git-pr
Switched to branch 'pr/59'
```
Thanks for your patience @thewtex

**Comment by jhlegarreta** [comment]
@thewtex  I assume the error:
```
error: unable to create file Utilities/GitSetup/git-pr (Permission denied)
```
has to do with the branch, although this:
```
D       Utilities/GitSetup/git-pr
```
indeed deleted the `git-pr` file 🤔

**Comment by thewtex** [comment]
Excellent, thanks for testing, @jhlegarreta !

> error: unable to create file Utilities/GitSetup/git-pr (Permission denied)

Yes, this should have to do with the recent addition of that file.

**Pull request merged**
